filters/urls.py
from django.contrib import admin
from django.urls import path
from filters import views

urlpatterns = [
    path('page_detail/<int:pk>/',views.page_detail, name='page_detail'),
    path('mypage/',views.my_page, name='mypage'),
    path('input/',views.test_input, name='input'),
    path('update/', views.test_update, name='update'),

    path('', views.LandingPage.as_view(), name='landing_page'),

]

sports_comunity/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('filters.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('restapi.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filters/models.py
from django.db import models
from django.conf import settings
from accounts.models import User


class Categories(models.Model):
    title = models.CharField(max_length=32)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Tag(models.Model):
    name = models.CharField(max_length=32, verbose_name="태그명")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="등록시간")

    def __str__(self):
        return self.name


class TestSet(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    categories = models.ForeignKey(Categories, on_delete=models.CASCADE, null=True)
    like_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    image = models.CharField(max_length=24, null=True)
    feature = models.CharField(max_length=150, null=True, blank=True)
    tag = models.ManyToManyField(Tag, verbose_name=Tag)

    def __str__(self):
        return self.title


class Comments(models.Model):
    article = models.ForeignKey(TestSet, on_delete=models.CASCADE)
    username = models.CharField(max_length=20, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body


class PostImage(models.Model):
    post = models.ForeignKey(TestSet, on_delete=models.CASCADE, null=True)
    temp = models.CharField(max_length=36, null=True)
    image = models.ImageField(upload_to="")
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    order = models.IntegerField(null=True)

filters/forms.py
from django import forms
from .models import TestSet, Comments, PostImage


class TestSetForm(forms.ModelForm):
    class Meta:
        model=TestSet
        fields = ['title', 'body',  'feature', 'tag', 'categories']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        exclude = ('body', 'user')



class PostImageFrom(forms.ModelForm):

    class Meta:
        model=PostImage
        fields = ['image']

filters/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from filters.models import TestSet, Comments, PostImage, Tag, Categories
from .forms import TestSetForm
import secrets
import time

from django.views.generic import ListView
# Create your views here.
@login_required
def my_page(request):
    data = TestSet.objects.filter(author=request.user).order_by('-created_at')
    context = {
        'data':data
    }
    return render(request, 'filters/profile.html', context=context)


def page_detail(request, pk):
    data = TestSet.objects.get(pk=pk)
    request.session['key'] = pk
    liked = data.like_user.filter(pk = request.user.pk)
    if len(liked) == 1:
        likes = True
    else:
        likes = False

    tag_list = list()
    for item in data.tag.all():
        tag_list.append(item.name)


    count_likes = len(data.like_user.all())
    context = {
        'user': request.user,
        'data':data,
        'likes':likes,
        'tags':tag_list,
        'count_likes':count_likes,
    }
    return render(request, 'filters/detail.html', context=context)

@login_required
def test_input(request):

    request.session['temp_article'] = secrets.token_hex(nbytes=8) + str(int(time.time()))

    if request.method == 'POST':
        # get information
        title = request.POST['title']
        body = request.POST['body']

        data = TestSet()
        data.title = title
        data.body = body
        data.author = request.user
        data.image = request.session['temp_article']
        data.feature = request.POST['feature']

        category = Categories.objects.get(pk=request.POST['categories'])
        data.categories = category
        data.save()

        tags = request.POST['tag'].split(',')

        for tag in tags:
            if not tag:
                continue
            else:
                tag = tag.strip()

                if len(Tag.objects.filter(name=tag)) == 0:
                    new_tag = Tag()
                    new_tag.name = tag
                    new_tag.save()
                    data.tag.add(new_tag)

        try:
            Image_object = PostImage.objects.get(temp=request.session['temp_article'])
            Image_object.post = data

        except:
            pass

        return redirect('page_detail', data.pk)

    forms = TestSetForm()
    context = {'form':forms}
    return render(request, 'filters/input.html', context=context)


def test_update(request):
    print(12345)
    pk = request.session['key']
    data = TestSet.objects.get(pk=pk)

    if data.author != request.user:
        return None
    form = TestSetForm(instance=data)
    request.session['temp_article'] = data.image
    if request.method == 'POST':
        title = request.POST['body']
        body = request.POST['body']

        data = TestSet()
        data.title = title
        data.body = body
        data.save()

    forms = TestSetForm()
    context = {
        'form':form,
        'pk': request.session['key']
    }
    return render(request, 'filters/update.html', context=context)



class LandingPage(ListView):
    model = TestSet
    template_name = 'filters/landing_page.html'
    def get_queryset(self):
        data = TestSet.objects.all().order_by('-created_at')
        return data

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

filters/templates/filters/detail.html
{% extends 'base/base.html' %}
{% load md_filter %}
{% load static %}
{% block body %}
<div>
{% if user == data.author %}
     <a href="{% url 'update' %}">글 수정하기</a>
{% endif %}

    <a href="{% url 'landing_page' %}"> 돌아가기</a>
</div>

<div>
    {% if "media" in data.feature %}
        <img id="featureImage" src="{{ data.feature }}" alt="">
    {% endif %}


</div>

<div>

    <a id="like-button"
       {% if user.is_authenticated %}
        onclick="likeCounters()"
       {% else %}
        href="/accounts/login"
       {% endif %}
    >
        {% if likes %}
           LIKE💛
        {% else %}
            UNLIKE🤍
        {% endif %}
    </a>

</div>

<span id="like_counts">

</span>

<div  id="contents">
    <h1>{{ data.title }}</h1>
    <p>{{ data.categories }}</p>
    <div>
        {{data.body|mark}}
    </div>

</div>

<div>


    {% for tag in tags %}
        <span class="uk-label uk-label-success">{{ tag }}</span>
    {% endfor %}


</div>

    <hr>
{% if user == data.author %}
    <form>
        <fieldset class="uk-fieldset">
            <legend class="uk-legend">Comments</legend>

            <div class="uk-margin">
                <textarea id="comment_body" class="uk-textarea" rows="5" placeholder="Textarea"></textarea>
                <p uk-margin>
                    <input class="uk-button uk-button-primary" type="button" value="쓰기" onclick="postComment()">
                </p>

            </div>
        </fieldset>
    </form>
{% endif %}


<div id="comments_list">

</div>
<div id="dummy" hidden>
    <div class="comments_item">
        <article class="uk-comment uk-comment-primary" style="margin-bottom: 3px">
            <header class="uk-comment-header">
                <div class="uk-grid-medium uk-flex-middle" uk-grid>
                    <div class="uk-width-auto">
                        <img class="uk-comment-avatar" src="{% static 'filters/img/user.png' %}" width="80" height="80" alt="">
                    </div>
                    <div class="uk-width-expand">
                        <h4 class="uk-comment-title uk-margin-remove"><a class="uk-link-reset comments_item_author" href="#"></a></h4>
                        <ul class="uk-comment-meta uk-subnav uk-subnav-divider uk-margin-remove-top">
                            <li><a href="#" class="comments_item_created"></a></li>
{#                            <li><a href="#">Reply</a></li>#}
                        </ul>
                    </div>
                </div>
            </header>
            <div class="uk-comment-body">
                <p class="comments_item_body"></p>
            </div>
        </article>
    </div>

</div>


<script src = {% static 'filters/function.js' %}></script>
<script>
    commentsInit()

    var likeData = '{{ likes }}'
    if(likeData ==='False'){
        document.getElementById("like-button").setAttribute('data', '0')
    }else{
        document.getElementById("like-button").setAttribute('data', '1')
    }
    console.log(document.getElementById("like-button").getAttribute('data'))
</script>
{% endblock %}

filters/templates/filters/input.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
{% endblock %}

{% block body %}




<button class="uk-button uk-button-default" type="button" uk-toggle="target: #offcanvas-flip">이미지 업로드</button>
    <hr>
<form  method="POST">{% csrf_token %}

    {{ form.title|add_class:"uk-input" }}


    {{ form.body | linebreaks}}
    {{ form.categories |add_class:"uk-input"}}
    <br>
    <p>썸네일 이미지</p>
    {{ form.feature|add_class:"uk-input" }}
    <hr>
    <p>tags</p>
    <input name="tag" type="text" class="uk-input">
    <hr>
    <input type="submit" value="저장" class="uk-button uk-button-primary" >
</form>



<div id="offcanvas-flip" uk-offcanvas="flip: true; overlay: true">
    <div class="uk-offcanvas-bar">
        <button class="uk-offcanvas-close" type="button" uk-close></button>
        <h3>이미지 관리</h3>
        <p>이미지를 업로드 후 업로드 된 이미지를 클릭하면 글에 이미지를 삽입할 수 있는 코드를 생성하여 글에 바로 삽입할 수 있습니다. </p>
        <div id="image_container"></div>
        <div class="js-upload uk-placeholder uk-text-center">
            <span uk-icon="icon: cloud-upload"></span>
            <span class="uk-text-middle">업로드 텍스트를 클릭해 주세요 </span>
            <div uk-form-custom>
                <input type="file" id="image" accept="image/*" onchange="setThumbnail();">
                <span class="uk-link">업로드</span>

            </div>
        </div>

        <hr>
        <div id="updatedImg"></div>

        <div id="thumb_dummy" hidden>
            <div class="uk-inline" >
                <div>
                    <div class="uk-position-top-right uk-overlay uk-overlay-primary">
                        <button class="uk-close-large" type="button" aria-label="Close" uk-close onclick="alert('delete?')"></button>
                    </div>
                    <img class="uk-object-cover" src="https://getuikit.com/docs/images/photo.jpg" width="1000" height="1000" alt=""
                         onclick="alert('copy')" style="aspect-ratio: 1 / 1;">
                </div>
            </div>

        </div>


    </div>
</div>

<script src="{% static 'filters/function.js' %}"></script>
<script>
imageInit()


var simplemde = new SimpleMDE({
    autosave: {
        enabled: false,
        uniqueId: "MyUniqueID",
        delay: 1000,
    },
    placeholder: '여기에 쓰세요',
    spellChecker: false,
    element: document.getElementById("id_body")

});
simplemde.value('');


</script>

{% endblock %}

filters/templates/filters/landing_page.html
{% extends 'base/base.html' %}
{% load static %}

{% block body %}
    <div>
    {% if user.is_authenticated %}
        <a href="{% url 'input' %}">글 작성하기</a>
        <a href="{% url 'mypage' %}">마이 페이지</a>
    {% else %}
        <a href="/accounts/signup">회원가입</a>
        <a href="/accounts/login">로그인</a>
    {% endif %}

    </div>
    <br>

    <div class="uk-child-width-1-2@m" uk-grid>
{% for datum in testset_list %}
    <div>
        <div class="uk-card uk-card-default">
            <div class="uk-card-media-top">
                {% if 'http' in datum.feature %}
                    <img src="{{ datum.feature }}" width="1800" height="1200" alt="" style="padding:5px;">
                {% else %}
                    <img src="{% static 'filters/img/blank.jpg' %}" width="1800" height="1200" alt="" style="padding:5px;">
                {% endif %}

            </div>

            <div class="uk-card-body">
                <div class="uk-width-expand">
                    <h3 class="uk-card-title uk-margin-remove-bottom">{{ datum.title }}</h3>
                    <p class="uk-text-meta uk-margin-remove-top"><time datetime="2016-04-01T19:00">April 01, 2016</time></p>
                    <p><span><a href="{% url 'page_detail' datum.pk %}" class="uk-button uk-button-text">Read more</a></span></p>
                </div>

            </div>

        </div>
    </div>

{% endfor %}


</div>





{% endblock %}

filters/templates/filters/profile.html
{% extends 'base/base.html' %}
{% load md_filter %}
{% load static %}

{% block body %}
<div>
    {% if user.is_authenticated %}
         <a href="{% url 'input' %}">새로 만들기</a>
    {% endif %}

</div>
<div class="uk-child-width-1-2@m" uk-grid>
{% for datum in data %}
    <div>
        <div class="uk-card uk-card-default">
            <div class="uk-card-media-top">
                {% if 'http' in datum.feature %}
                    <img src="{{ datum.feature }}" width="1800" height="1200" alt="" style="padding:5px;">
                {% else %}
                    <img src="{% static 'filters/img/blank.jpg' %}" width="1800" height="1200" alt="" style="padding:5px;">
                {% endif %}

            </div>

            <div class="uk-card-body">
                <div class="uk-width-expand">
                    <h3 class="uk-card-title uk-margin-remove-bottom">{{ datum.title }}</h3>
                    <p class="uk-text-meta uk-margin-remove-top"><time datetime="2016-04-01T19:00">April 01, 2016</time></p>
                    <p><span><a href="{% url 'page_detail' datum.pk %}" class="uk-button uk-button-text">Read more</a></span></p>
                </div>

            </div>

        </div>
    </div>

{% endfor %}


</div>



{% for datum in data %}
    <p><a href="{% url 'page_detail' datum.pk %}">{{ datum.title }}</a> - <span>{{ datum.like_user.all.count }}</span></p>
{% endfor %}
{% endblock %}

filters/templates/filters/update.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>

{% endblock %}

{% block body %}

<button class="uk-button uk-button-default" type="button" uk-toggle="target: #offcanvas-flip">이미지 업로드</button>
    <hr>

<form method="POST">{% csrf_token %}
    <fieldset class="uk-fieldset">
        <legend class="uk-legend">글 수정하기</legend>
        <div class="uk-margin">
            <input class="uk-input" id="id_title" type="text">
        </div>

        <input id="id_body" type="textarea">

        <br>
        <p>썸네일 이미지</p>
        {{ form.feature|add_class:"uk-input" }}
        <hr>
        <p>tags</p>
        <input id="tagsName" name="tag" type="text" class="uk-input">

        <hr>
        <input class="uk-button uk-button-primary" type="button" onclick="updateString({{ pk }})" value="ok">
    </fieldset>


</form>


<div id="offcanvas-flip" uk-offcanvas="flip: true; overlay: true">
    <div class="uk-offcanvas-bar">
        <button class="uk-offcanvas-close" type="button" uk-close></button>
        <h3>이미지 관리</h3>
        <p>이미지를 업로드 후 업로드 된 이미지를 클릭하면 글에 이미지를 삽입할 수 있는 코드를 생성하여 글에 바로 삽입할 수 있습니다. </p>
        <div id="image_container"></div>
        <div class="js-upload uk-placeholder uk-text-center">
            <span uk-icon="icon: cloud-upload"></span>
            <span class="uk-text-middle">업로드 텍스트를 클릭해 주세요 </span>
            <div uk-form-custom>
                <input type="file" id="image" accept="image/*" onchange="setThumbnail();">
                <span class="uk-link">업로드</span>

            </div>
        </div>
        <br>
        <form method="POST">

        </form>
        <hr>
        <div id="updatedImg"></div>
        <div id="thumb_dummy" hidden>
            <div class="uk-inline" >
                <div>
                    <div class="uk-position-top-right uk-overlay uk-overlay-primary">
                        <button class="uk-close-large" type="button" aria-label="Close" uk-close onclick="alert('delete?')"></button>
                    </div>
                    <img class="uk-object-cover" src="https://getuikit.com/docs/images/photo.jpg" width="1000" height="1000" alt=""
                         onclick="alert('copy')" style="aspect-ratio: 1 / 1;">
                </div>
            </div>

        </div>

    </div>
</div>



<script src="{% static 'filters/function.js' %}"></script>
<script>
    tagInit()
    function tagInit() {
        fetch("/api/tagUpdater/")
            .then((response) => response.json())
            .then((data) => fillTheTags(data))
    }



    function fillTheTags(data) {
        document.getElementById('tagsName').value = data['tag']
    }

    imageInit()
    var simplemde = new SimpleMDE({
        spellChecker: false,
        element: document.getElementById("id_body")
    });
    textInit()

    function textInit() {
        fetch("/api/TestSet/")
          .then((response) => response.json())
          .then((data) => load_text_data(data));
    }


    function load_text_data(data) {
        document.getElementById('id_title').value = data.title
        simplemde.value(data.body)
    }


    function updateString(pk) {
        let targetTitle = document.getElementById('id_title').value
        let targetValue = simplemde.value();
        let targetFeature = document.querySelectorAll('.uk-input')[1].value
        var headers = new Headers();
        var csrftoken = getCookie('csrftoken');
        headers.append('X-CSRFToken', csrftoken);
        headers.append('Accept', 'application/json, text/plain, */*');
        headers.append('Content-Type', 'application/x-www-form-urlencoded');
        fetch("/api/TestSet/", {
            method: "PUT",
            headers: headers,
            body: JSON.stringify({
                title: targetTitle,
                body: targetValue,
                feature: targetFeature,

            }),
        })
        .then((response) => response.json())
        .then((data) => movePage(pk));
    }

    function movePage(pk) {
        updateTags(pk)
        //location.replace(`/page_detail/${pk}/`)
    }


    function updateTags(pk) {
        let tagsList = document.getElementById('tagsName').value

        console.log(1)
        var headers = new Headers();
        var csrftoken = getCookie('csrftoken');
        headers.append('X-CSRFToken', csrftoken);
        headers.append('Accept', 'application/json, text/plain, */*');
        headers.append('Content-Type', 'application/x-www-form-urlencoded');
        fetch("/api/tagUpdater/", {
            method: "PUT",
            headers: headers,
            body: JSON.stringify({
                tags: tagsList,

            }),
        })
        .then((response) => response.json())
        .then((data) => location.replace(`/page_detail/${pk}/`) );

    }


</script>

{% endblock %}